# Generated by Django 6.0.3 on 2026-03-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isOnline',
            field=models.BooleanField(default=False),
        ),
    ]
